"""
Bronze layer schema definitions.

Bronze tables contain raw, minimally transformed data with full provenance.
This is the "source of truth" for what was ingested.

Design principles:
- utterance_id (hash) is the stable PK for joins/references
- utterance_key (human-readable) is for debugging/inspection
- audio_relpath is stable across mounts; resolve via paths.py
- phonemes_source distinguishes ground_truth vs corpus_provided vs generated
- meta map holds corpus-specific overflow (promote to columns in silver if needed)
"""

from pyspark.sql.types import (
    FloatType,
    IntegerType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

# Allowed values for phonemes_source
PHONEME_SOURCES = frozenset({
    "ground_truth",      # Verified correct (rare)
    "corpus_provided",   # Provided by corpus but quality unknown
    "generated",         # Generated by G2P (pyopenjtalk, etc.)
    "none",              # No phonemes available
    "unknown",           # Source unclear
})

BRONZE_UTTERANCES_SCHEMA = StructType([
    # =========================
    # Primary identifiers
    # =========================
    StructField("utterance_id", StringType(), nullable=False),   # sha1(...)[:16]
    StructField("utterance_key", StringType(), nullable=False),  # human-readable
    StructField("dataset", StringType(), nullable=False),
    StructField("speaker_id", StringType(), nullable=False),
    StructField("speaker_name", StringType(), nullable=True),
    StructField("subset", StringType(), nullable=False),
    StructField("corpus_utt_id", StringType(), nullable=False),

    # =========================
    # Audio fields
    # =========================
    StructField("audio_relpath", StringType(), nullable=False),  # stable relpath under DATA_ROOT/data/
    StructField("audio_format", StringType(), nullable=False),   # wav/flac/mp3
    StructField("sample_rate", IntegerType(), nullable=False),
    StructField("channels", IntegerType(), nullable=False),
    StructField("duration_sec", FloatType(), nullable=False),

    # =========================
    # Text fields
    # =========================
    StructField("text_raw", StringType(), nullable=False),
    StructField("text_norm_raw", StringType(), nullable=True),   # corpus-provided norm if available

    # =========================
    # Phonemes as provided by source (if any)
    # =========================
    StructField("phonemes_source", StringType(), nullable=False),  # ground_truth|corpus_provided|generated|none|unknown
    StructField("phonemes_raw", StringType(), nullable=True),

    # =========================
    # Provenance
    # =========================
    StructField("ingest_version", StringType(), nullable=False),
    StructField("source_version", StringType(), nullable=True),
    StructField("source_url", StringType(), nullable=True),
    StructField("source_archive_checksum", StringType(), nullable=True),
    StructField("audio_checksum", StringType(), nullable=True),
    StructField("ingested_at", TimestampType(), nullable=False),

    # =========================
    # Overflow metadata
    # =========================
    StructField("meta", MapType(StringType(), StringType(), valueContainsNull=True), nullable=True),
])
