"""
Baseline Mel Model Training Pipeline.

Trains a simple encoder-decoder model for pipeline validation.

Usage:
    koe train baseline jsut --config configs/training/baseline.yaml
    koe train baseline jsut --max-steps 1000 --batch-size 8
"""

import argparse
import hashlib
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
import yaml

from modules.data_engineering.common.paths import paths
from modules.training.audio import MelConfig
from modules.training.common import create_train_val_loaders, EventLogger
from modules.training.dataloading import TTSBatch
from modules.training.models.baseline_mel import create_model, BaselineModelConfig


def compute_config_hash(config: dict) -> str:
    """Compute hash of config for checkpoint validation."""
    config_str = json.dumps(config, sort_keys=True)
    return hashlib.md5(config_str.encode()).hexdigest()[:8]


def load_config(config_path: Path) -> dict:
    """Load YAML config file."""
    with open(config_path) as f:
        return yaml.safe_load(f)


def get_git_commit() -> str:
    """Get current git commit hash."""
    import subprocess
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=5
        )
        return result.stdout.strip() if result.returncode == 0 else "unknown"
    except Exception:
        return "unknown"


def write_run_md(
    output_dir: Path,
    config: dict,
    dataset: str,
    cache_dir: Path,
    n_params: int,
    resume_path: Optional[Path] = None,
) -> None:
    """
    Write auto-generated RUN.md with run metadata.

    This serves as a lightweight MLflow-lite for tracking runs.
    """
    git_commit = get_git_commit()
    config_hash = compute_config_hash(config)
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")

    # Extract key config values
    run_name = config.get("run", {}).get("name", "unknown")
    max_steps = config.get("train", {}).get("max_steps", 0)
    batch_size = config.get("data", {}).get("batch_size", 0)
    lr = config.get("optim", {}).get("lr", 0)

    content = f"""# Run: {output_dir.name}

## Metadata
- **Created**: {timestamp}
- **Git commit**: `{git_commit}`
- **Config hash**: `{config_hash}`

## Dataset
- **Dataset**: {dataset}
- **Cache**: `{cache_dir.name}`

## Model
- **Type**: baseline_mel
- **Parameters**: {n_params:,}

## Training Config
- **Max steps**: {max_steps}
- **Batch size**: {batch_size}
- **Learning rate**: {lr}
- **AMP**: {config.get("run", {}).get("amp", False)}

## Resume
- **From**: {resume_path if resume_path else "None (fresh start)"}

## Checkpoints
| Checkpoint | Step | Val Loss | Notes |
|------------|------|----------|-------|
| *(updated during training)* | | | |

## Eval Results
| Eval Tag | mel_l1 | mel_l2 | snr_db | Notes |
|----------|--------|--------|--------|-------|
| *(updated after eval)* | | | | |

---
*Auto-generated by koe-tts training pipeline*
"""

    with open(output_dir / "RUN.md", "w") as f:
        f.write(content)


def update_run_md_checkpoint(
    output_dir: Path,
    checkpoint_name: str,
    step: int,
    val_loss: float,
    notes: str = "",
) -> None:
    """Append checkpoint info to RUN.md."""
    run_md = output_dir / "RUN.md"
    if not run_md.exists():
        return

    # Read existing content
    with open(run_md) as f:
        content = f.read()

    # Find checkpoint table and append
    marker = "| *(updated during training)* | | | |"
    new_row = f"| {checkpoint_name} | {step} | {val_loss:.4f} | {notes} |"

    if marker in content:
        content = content.replace(marker, f"{new_row}\n{marker}")
        with open(run_md, "w") as f:
            f.write(content)


def save_checkpoint(
    path: Path,
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    scaler: Optional[torch.amp.GradScaler],
    step: int,
    epoch: int,
    best_val_loss: float,
    config: dict,
) -> None:
    """
    Save checkpoint with full training state.

    Checkpoint contract:
    - model_state: Model weights
    - optim_state: Optimizer state (for resume)
    - scaler_state: AMP scaler state (if using AMP)
    - step: Global step count
    - epoch: Current epoch
    - best_val_loss: Best validation loss seen
    - config_hash: Hash of config for validation
    - config: Full config dict
    - saved_at: ISO timestamp
    """
    checkpoint = {
        "model_state": model.state_dict(),
        "optim_state": optimizer.state_dict(),
        "scaler_state": scaler.state_dict() if scaler is not None else None,
        "step": step,
        "epoch": epoch,
        "best_val_loss": best_val_loss,
        "config_hash": compute_config_hash(config),
        "config": config,
        "saved_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(checkpoint, path)


def load_checkpoint(
    path: Path,
    model: torch.nn.Module,
    optimizer: torch.optim.Optimizer,
    scaler: Optional[torch.amp.GradScaler],
    config: dict,
    device: str,
) -> tuple[int, int, float]:
    """
    Load checkpoint and restore training state.

    Returns:
        Tuple of (step, epoch, best_val_loss)
    """
    checkpoint = torch.load(path, map_location=device, weights_only=True)

    # Validate config hash
    expected_hash = compute_config_hash(config)
    saved_hash = checkpoint.get("config_hash", "")
    if saved_hash and saved_hash != expected_hash:
        print(f"Warning: Config hash mismatch (saved={saved_hash}, current={expected_hash})")
        print("Training may not resume correctly if config changed significantly.")

    model.load_state_dict(checkpoint["model_state"])
    optimizer.load_state_dict(checkpoint["optim_state"])

    if scaler is not None and checkpoint.get("scaler_state"):
        scaler.load_state_dict(checkpoint["scaler_state"])

    return (
        checkpoint["step"],
        checkpoint["epoch"],
        checkpoint.get("best_val_loss", float("inf")),
    )


def compute_loss(
    mel_pred: torch.Tensor,
    mel_target: torch.Tensor,
    mel_mask: torch.Tensor,
) -> tuple[torch.Tensor, dict]:
    """
    Compute L1 + L2 loss on mel predictions.

    Args:
        mel_pred: [B, n_mels, T] predicted mel
        mel_target: [B, n_mels, T] target mel
        mel_mask: [B, T] True for valid frames

    Returns:
        Total loss and dict of individual losses
    """
    # Expand mask to [B, n_mels, T]
    mask = mel_mask.unsqueeze(1).float()

    # Compute masked losses
    l1_loss = (F.l1_loss(mel_pred, mel_target, reduction='none') * mask).sum()
    l2_loss = (F.mse_loss(mel_pred, mel_target, reduction='none') * mask).sum()

    # Normalize by number of valid frames
    n_frames = mask.sum() * mel_pred.size(1)  # n_mels * valid_frames
    l1_loss = l1_loss / n_frames
    l2_loss = l2_loss / n_frames

    # Combined loss
    total_loss = l1_loss + 0.5 * l2_loss

    return total_loss, {"l1": l1_loss.item(), "l2": l2_loss.item()}


def train_step(
    model: torch.nn.Module,
    batch: TTSBatch,
    optimizer: torch.optim.Optimizer,
    scaler: Optional[torch.amp.GradScaler],
    grad_clip: float,
    device: str,
    use_amp: bool,
) -> dict:
    """
    Single training step.

    Returns:
        Dict with loss, grad_norm, etc.
    """
    model.train()
    batch = batch.to(device)

    optimizer.zero_grad()

    # Forward pass with optional AMP
    with torch.amp.autocast('cuda', enabled=use_amp):
        mel_pred = model(
            phonemes=batch.phonemes,
            phoneme_mask=batch.phoneme_mask,
            mel_lens=batch.mel_lens,
            mel_mask=batch.mel_mask,
        )
        loss, loss_dict = compute_loss(mel_pred, batch.mels, batch.mel_mask)

    # Backward pass
    if scaler is not None:
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
    else:
        loss.backward()

    # Gradient clipping
    grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)

    # Optimizer step
    if scaler is not None:
        scaler.step(optimizer)
        scaler.update()
    else:
        optimizer.step()

    return {
        "loss": loss.item(),
        "grad_norm": grad_norm.item() if isinstance(grad_norm, torch.Tensor) else grad_norm,
        **loss_dict,
    }


@torch.no_grad()
def validate(
    model: torch.nn.Module,
    val_loader: torch.utils.data.DataLoader,
    device: str,
    max_batches: Optional[int] = None,
) -> dict:
    """
    Run validation loop.

    Returns:
        Dict with average validation metrics
    """
    model.eval()

    total_loss = 0.0
    total_l1 = 0.0
    total_l2 = 0.0
    n_batches = 0

    for i, batch in enumerate(val_loader):
        if batch is None:
            continue
        if max_batches and i >= max_batches:
            break

        batch = batch.to(device)

        mel_pred = model(
            phonemes=batch.phonemes,
            phoneme_mask=batch.phoneme_mask,
            mel_lens=batch.mel_lens,
            mel_mask=batch.mel_mask,
        )
        loss, loss_dict = compute_loss(mel_pred, batch.mels, batch.mel_mask)

        total_loss += loss.item()
        total_l1 += loss_dict["l1"]
        total_l2 += loss_dict["l2"]
        n_batches += 1

    if n_batches == 0:
        return {"val_loss": float("inf"), "val_l1": 0, "val_l2": 0}

    return {
        "val_loss": total_loss / n_batches,
        "val_l1": total_l1 / n_batches,
        "val_l2": total_l2 / n_batches,
    }


def find_cache_dir(dataset: str, snapshot_id: Optional[str] = None) -> Path:
    """Find cache directory for dataset."""
    from modules.data_engineering.common.paths import paths

    cache_base = paths.cache / dataset

    if snapshot_id:
        cache_dir = cache_base / snapshot_id
        if not cache_dir.exists():
            raise FileNotFoundError(f"Cache not found: {cache_dir}")
        return cache_dir

    # Try 'latest' symlink
    latest = cache_base / "latest"
    if latest.exists():
        return latest.resolve()

    # Find most recent
    snapshots = sorted(cache_base.glob("*"), key=lambda p: p.stat().st_mtime, reverse=True)
    snapshots = [s for s in snapshots if s.is_dir() and s.name != "latest"]
    if not snapshots:
        raise FileNotFoundError(f"No cache found for {dataset}. Run: koe cache create {dataset}")

    return snapshots[0]


def train(
    config: dict,
    dataset: str,
    snapshot_id: Optional[str] = None,
    resume_path: Optional[Path] = None,
    output_dir: Optional[Path] = None,
) -> dict:
    """
    Main training function.

    Args:
        config: Training configuration
        dataset: Dataset name
        snapshot_id: Cache snapshot ID (None = latest)
        resume_path: Path to checkpoint to resume from
        output_dir: Override output directory

    Returns:
        Dict with training results
    """
    # Setup
    run_name = config["run"]["name"]
    seed = config["run"]["seed"]
    device = config["run"]["device"]
    use_amp = config["run"]["amp"] and device == "cuda"

    torch.manual_seed(seed)
    if device == "cuda":
        torch.cuda.manual_seed(seed)

    # Output directory
    if output_dir is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = paths.runs / f"{dataset}_{run_name}_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save config
    with open(output_dir / "config.yaml", "w") as f:
        yaml.dump(config, f, default_flow_style=False)

    # Initialize event/metrics logger
    events = EventLogger(output_dir)
    metrics_file = events.metrics_file

    print("=" * 70)
    print("BASELINE MEL TRAINING")
    print("=" * 70)
    print(f"Dataset: {dataset}")
    print(f"Output: {output_dir}")
    print(f"Device: {device}")
    print(f"AMP: {use_amp}")
    print()

    # Find cache
    cache_dir = find_cache_dir(dataset, snapshot_id)
    print(f"Cache: {cache_dir}")

    # Create mel config (must match Stage 1)
    mel_cfg = config.get("mel", {})
    mel_config = MelConfig(
        sample_rate=mel_cfg.get("sample_rate", 22050),
        n_mels=mel_cfg.get("n_mels", 80),
        n_fft=mel_cfg.get("n_fft", 1024),
        hop_length=mel_cfg.get("hop_length", 256),
        win_length=mel_cfg.get("win_length", 1024),
        f_min=mel_cfg.get("f_min", 0),
        f_max=mel_cfg.get("f_max", 8000),
    )

    # Create dataloaders (using unified factory for memory safety)
    data_cfg = config.get("data", {})
    batch_size = data_cfg.get("batch_size", 16)
    num_workers = data_cfg.get("num_workers", 4)
    segment_seconds = data_cfg.get("segment_seconds", None)
    speaker_balanced = data_cfg.get("speaker_balanced", None)

    print(f"Batch size: {batch_size}")
    print(f"Workers: {num_workers}")
    if segment_seconds:
        print(f"Segment: {segment_seconds}s")

    train_loader, val_loader, speaker_vocab, num_speakers = create_train_val_loaders(
        cache_dir=cache_dir,
        mel_config=mel_config,
        batch_size=batch_size,
        num_workers=num_workers,
        segment_seconds=segment_seconds,
        speaker_balanced=speaker_balanced,
        seed=seed,
    )

    if num_speakers > 1:
        print(f"Speakers: {num_speakers}")
        if speaker_balanced is not False:
            print("Train sampler: speaker-balanced")

    print(f"Train batches: {len(train_loader)}")
    print(f"Val batches: {len(val_loader)}")
    print()

    # Create model
    model = create_model(config)
    model = model.to(device)
    n_params = model.count_parameters()
    print(f"Model parameters: {n_params:,}")

    # Write RUN.md
    write_run_md(
        output_dir=output_dir,
        config=config,
        dataset=dataset,
        cache_dir=cache_dir,
        n_params=n_params,
        resume_path=resume_path,
    )

    # Optimizer
    optim_cfg = config.get("optim", {})
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=optim_cfg.get("lr", 2e-4),
        weight_decay=optim_cfg.get("weight_decay", 0.01),
        betas=tuple(optim_cfg.get("betas", [0.9, 0.98])),
    )

    # AMP scaler
    scaler = torch.amp.GradScaler('cuda') if use_amp else None

    # Training config
    train_cfg = config.get("train", {})
    max_steps = train_cfg.get("max_steps", 20000)
    log_every = train_cfg.get("log_every_steps", 50)
    val_every = train_cfg.get("val_every_steps", 1000)
    save_every = train_cfg.get("save_every_steps", 1000)
    grad_clip = optim_cfg.get("grad_clip", 1.0)
    max_val_batches = data_cfg.get("max_val_batches", 50)

    # Resume from checkpoint
    step = 0
    epoch = 0
    best_val_loss = float("inf")

    if resume_path and resume_path.exists():
        print(f"Resuming from: {resume_path}")
        step, epoch, best_val_loss = load_checkpoint(
            resume_path, model, optimizer, scaler, config, device
        )
        print(f"  Step: {step}, Epoch: {epoch}, Best val loss: {best_val_loss:.4f}")
        print()

    # Training loop
    print("=" * 70)
    print(f"Starting training (step {step} -> {max_steps})")
    print("=" * 70)
    print()
    print(f"{'Step':>8} | {'Loss':>8} | {'L1':>8} | {'L2':>8} | {'GradNorm':>8} | {'LR':>10} | {'Time':>6}")
    print("-" * 70)

    train_iter = iter(train_loader)
    start_time = time.time()
    step_times = []

    while step < max_steps:
        # Get next batch
        try:
            batch = next(train_iter)
        except StopIteration:
            epoch += 1
            train_iter = iter(train_loader)
            batch = next(train_iter)

        if batch is None:
            continue

        # Guardrail: require labeled data (phonemes/durations)
        if not batch.has_text:
            raise ValueError(
                f"This pipeline requires labeled text/phonemes, but batch has "
                f"{batch.n_labeled}/{batch.is_labeled.numel()} labeled samples. "
                "Tier 1 segment manifests are unlabeled. Use a full-utterance manifest "
                "or wait for Tier 2 labeling."
            )

        step_start = time.time()

        # Training step
        metrics = train_step(
            model, batch, optimizer, scaler, grad_clip, device, use_amp
        )

        step += 1
        step_time = time.time() - step_start
        step_times.append(step_time)

        # Logging
        if step % log_every == 0:
            lr = optimizer.param_groups[0]["lr"]
            avg_step_time = sum(step_times[-100:]) / len(step_times[-100:])
            print(
                f"{step:>8} | {metrics['loss']:>8.4f} | {metrics['l1']:>8.4f} | "
                f"{metrics['l2']:>8.4f} | {metrics['grad_norm']:>8.4f} | {lr:>10.2e} | "
                f"{avg_step_time:>5.2f}s"
            )

            # Write metrics to jsonl for dashboard
            metrics_row = {
                "step": step,
                "epoch": epoch,
                "total_loss": metrics["loss"],
                "mel_loss": metrics["l1"],
                "l2_loss": metrics["l2"],
                "g_grad_norm": metrics["grad_norm"],
                "lr": lr,
            }
            with open(metrics_file, "a") as f:
                f.write(json.dumps(metrics_row) + "\n")

        # Validation
        if step % val_every == 0:
            val_metrics = validate(model, val_loader, device, max_val_batches)
            print(f"         | Val loss: {val_metrics['val_loss']:.4f} (L1: {val_metrics['val_l1']:.4f}, L2: {val_metrics['val_l2']:.4f})")

            # Save best model
            if val_metrics["val_loss"] < best_val_loss:
                best_val_loss = val_metrics["val_loss"]
                save_checkpoint(
                    output_dir / "checkpoints" / "best.pt",
                    model, optimizer, scaler, step, epoch, best_val_loss, config
                )
                update_run_md_checkpoint(output_dir, "best.pt", step, best_val_loss, "new best")
                print(f"         | New best model saved (val_loss: {best_val_loss:.4f})")

        # Save checkpoint
        if step % save_every == 0:
            save_checkpoint(
                output_dir / "checkpoints" / f"step_{step:06d}.pt",
                model, optimizer, scaler, step, epoch, best_val_loss, config
            )

    # Final save
    save_checkpoint(
        output_dir / "checkpoints" / "final.pt",
        model, optimizer, scaler, step, epoch, best_val_loss, config
    )
    update_run_md_checkpoint(output_dir, "final.pt", step, best_val_loss, "final")

    # Final validation
    final_val = validate(model, val_loader, device, max_val_batches)

    total_time = time.time() - start_time
    print()
    print("=" * 70)
    print("TRAINING COMPLETE")
    print("=" * 70)
    print(f"Total steps: {step}")
    print(f"Total time: {total_time / 60:.1f} minutes")
    print(f"Final val loss: {final_val['val_loss']:.4f}")
    print(f"Best val loss: {best_val_loss:.4f}")
    print(f"Checkpoints: {output_dir / 'checkpoints'}")
    print("=" * 70)

    return {
        "step": step,
        "best_val_loss": best_val_loss,
        "final_val_loss": final_val["val_loss"],
        "output_dir": str(output_dir),
    }


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Train baseline mel model")
    parser.add_argument("dataset", help="Dataset name (jsut, jvs)")
    parser.add_argument(
        "--config", "-c",
        type=Path,
        default=Path("configs/training/baseline.yaml"),
        help="Config file path"
    )
    parser.add_argument("--snapshot", "-s", help="Cache snapshot ID")
    parser.add_argument("--resume", "-r", type=Path, help="Resume from checkpoint")
    parser.add_argument("--output-dir", "-o", type=Path, help="Output directory")

    # Config overrides
    parser.add_argument("--max-steps", type=int, help="Override max_steps")
    parser.add_argument("--batch-size", type=int, help="Override batch_size")
    parser.add_argument("--lr", type=float, help="Override learning rate")
    parser.add_argument("--no-amp", action="store_true", help="Disable AMP")

    args = parser.parse_args()

    # Load config
    if args.config.exists():
        config = load_config(args.config)
    else:
        print(f"Config not found: {args.config}")
        print("Using default config")
        config = {
            "run": {"name": "baseline_mel", "seed": 42, "device": "cuda", "amp": True},
            "data": {"batch_size": 16, "num_workers": 4},
            "mel": {"sample_rate": 22050, "n_mels": 80, "hop_length": 256},
            "model": {"d_model": 256, "n_conv_layers_enc": 6, "n_conv_layers_dec": 4},
            "optim": {"lr": 2e-4, "weight_decay": 0.01, "grad_clip": 1.0},
            "train": {"max_steps": 20000, "log_every_steps": 50, "val_every_steps": 1000, "save_every_steps": 1000},
        }

    # Apply overrides
    if args.max_steps:
        config["train"]["max_steps"] = args.max_steps
    if args.batch_size:
        config["data"]["batch_size"] = args.batch_size
    if args.lr:
        config["optim"]["lr"] = args.lr
    if args.no_amp:
        config["run"]["amp"] = False

    # Train
    result = train(
        config=config,
        dataset=args.dataset,
        snapshot_id=args.snapshot,
        resume_path=args.resume,
        output_dir=args.output_dir,
    )

    return 0 if result["best_val_loss"] < float("inf") else 1


if __name__ == "__main__":
    sys.exit(main())
